### ISSUE TITLE
t.size.rbt does not put the node inR

### ISSUE THREAD

**Issue by klkblake** [dmbarbour/awelon#23]
In the case of the empty tree, t.size.rbt returns the empty tree. However, in the case of a tree with a node, it returns the node directly, not the tree containing it! The obvious fix is adding `swap inR swap` to that branch.

**Comment by dmbarbour** [comment]
Thanks. I probably should get around to finishing RBTs, eventually. But I'd like to be doing this via Wikilon. :)
